### ISSUE TITLE
Please choose an open-source license: no choice means closed source!

### ISSUE THREAD

**Issue by Naereen** [EduardoRFS/reason-mobile#22]
Hi there,
Could you choose an open-source license for this project and add a `LICENSE` file?
No choice means closed source by default, see GitHub's page on <https://choosealicense.com/no-permission/>
Thanks, regards, @Naereen

**Comment by EduardoRFS** [comment]
@Naereen thank you for the issue, had forgot about it. Is this enough?

https://github.com/EduardoRFS/reason-mobile/blob/master/LICENSE

**Comment by Naereen** [comment]
Perfect!
