### ISSUE TITLE
error with esy generate

### ISSUE THREAD

**Issue by bentxt** [EduardoRFS/reason-mobile#5]
Specs:
Version 10.15.7
OCaml toplevel, version 4.10.0
esy 6.6

Inspired by the readme: 
cd hello-reason
...
esy add -D generate@EduardoRFS/reason-mobile:generate.json
esy generate ios.simulator.x86_64

Error log:

.... installing @_ios.simulator.x86_64/_opam_ocaml_migrate_parsetree@path:.mocks/c1dbeec1/esy.json@d41d8                                                                                                        info installing: done
error: expected string
  reading package metadata from ~/.esy/source/i/__ios.simulator.x86__64__s____esy__ocaml__reason__de785ef5
  reading manifest @_ios.simulator.x86_64/_esy_ocaml_reason@path:.mocks/188902d4/esy.json@d41d8cd9
esy: exiting due to errors above
Fatal error: exception File "generate/src/Esy.re", line 292, characters 11-17: Assertion failed
Raised at file "generate/src/Esy.re", line 292, characters 11-24
Called from file "src/core/lwt.ml", line 1867, characters 23-26
Re-raised at file "src/core/lwt.ml", line 3027, characters 20-29
Called from file "src/unix/lwt_main.ml", line 27, characters 10-20
Called from file "src/unix/lwt_main.ml", line 114, characters 8-13
Re-raised at file "src/unix/lwt_main.ml", line 120, characters 4-13
Called from file "generate/src/Generate.re", line 431, characters 9-31

**Comment by EduardoRFS** [comment]
@bentxt you need esy@0.6.7

**Comment by bentxt** [comment]
thanks, thats works.
on a different note, maybe in the future you could let the author close the issue.
